networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
      - .env
    build:
      context: .
      dockerfile: Backend/rabbitmq/Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - transcendence_network

  profile-service:
    container_name: profile-service
    image: profile-service
    build:
      context: .
      dockerfile: Backend/profile_service/Dockerfile
    env_file:
      - .env
    # ports:
    #   - 8001:8001
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq
  
  user-service:
    container_name: user-service
    image: user-service
    build:
      context: .
      dockerfile: Backend/user_service/Dockerfile
    env_file:
      - .env
    # ports:
    #   - 8001:8001
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  token-service:
    container_name: token-service
    image: token-service
    build:
      context: .
      dockerfile: Backend/token_service/Dockerfile
    env_file:
      - .env
    # ports:
    #   - 8000:8000
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:443
    networks:
      - transcendence_network
    depends_on:
      - user-service
      - token-service
      - profile-service