networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
      - .env
    build:
      context: .
      dockerfile: Backend/rabbitmq/Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - transcendence_network

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: .
      dockerfile: Backend/user_management/Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8001
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  auth-service:
    container_name: auth-service
    image: auth-service
    build:
      context: .
      dockerfile: Backend/auth_service/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  game-history:
    container_name: game-history
    image: game-history
    build:
      context: .
      dockerfile: Backend/game_history/Dockerfile
    env_file:
      - .env
    ports:
      - 8002:8002
    networks:
      - transcendence_network

  game-stats-service:
    container_name: game-stats-service
    image: game-stats-service
    build:
      context: .
      dockerfile: Backend/game_stats_service/Dockerfile
    env_file:
      - .env
    ports:
      - 8003:8003
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:443
    networks:
      - transcendence_network
    depends_on:
      - user-service
      - auth-service

  game-server:
    container_name: game-server
    image: game-server
    build:
      context: .
      dockerfile: Game_server/Dockerfile
    env_file:
      - .env
    ports:
      - 8002:8002
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq