networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
      - .env
    build:
      context: .
      dockerfile: Backend/rabbitmq/Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - transcendence_network

  user_service:
    container_name: user_service
    image: user_service
    build:
      context: .
      dockerfile: Backend/user_management/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  auth_service:
    container_name: auth_service
    image: auth_service
    build:
      context: .
      dockerfile: Backend/auth_service/Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8000
    networks:
      - transcendence_network
    depends_on:
      - rabbitmq

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:443
    networks:
      - transcendence_network
    depends_on:
      - user_service
      - auth_service