networks:
  transcendence_network:
    name: transcendence_network
    driver: bridge

services:

  user_service:
    container_name: user_service
    image: user_service
    build:
      context: .
      dockerfile: Backend/user-management/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - transcendence_network

  auth_service:
    container_name: auth_service
    image: auth_service
    build:
      context: .
      dockerfile: Backend/auth-service/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - transcendence_network
