networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: API/API_container/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - mynetwork