networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: API/API_container/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    container_name: database
    hostname: database
    image: database
    build:
      context: .
      dockerfile: API/Database_container/Dockerfile
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always
    networks:
      - mynetwork