name: Merge Develop to Main

on:
  pull_request:
    branches:
      - develop

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge develop into main
        run: |
          git checkout main
          git merge develop --no-ff -m "Merging develop into main"
          git push origin main
